// <auto-generated />
using System;
using ARCompletions.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ARCompletions.migrations
{
    [DbContext(typeof(ARCompletionsContext))]
    [Migration("20260402063252_DropLegacyVendorAndFaqSchema")]
    partial class DropLegacyVendorAndFaqSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ARCompletions.Domain.AuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("TargetId")
                        .HasColumnType("text");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ARCompletions.Domain.BotAuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditId"));

                    b.Property<string>("ActionType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("text");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<string>("TargetId")
                        .HasColumnType("text");

                    b.Property<string>("TargetTable")
                        .HasColumnType("text");

                    b.HasKey("AuditId");

                    b.ToTable("bot_audit_logs", (string)null);
                });

            modelBuilder.Entity("ARCompletions.Domain.BotConstantsConfig", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasColumnType("text");

                    b.Property<string>("ConfigValue")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("ValueType")
                        .HasColumnType("text");

                    b.HasKey("ConfigKey");

                    b.ToTable("bot_constants_config", (string)null);
                });

            modelBuilder.Entity("ARCompletions.Domain.BotContextMessage", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MessageId"));

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetaAliasTerm")
                        .HasColumnType("text");

                    b.Property<string>("MetaCandidates")
                        .HasColumnType("text");

                    b.Property<string>("MetaMatchedFaqId")
                        .HasColumnType("text");

                    b.Property<string>("MetaRoute")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Ts")
                        .HasColumnType("bigint");

                    b.HasKey("MessageId");

                    b.ToTable("bot_context_messages", (string)null);
                });

            modelBuilder.Entity("ARCompletions.Domain.BotConversationSetting", b =>
                {
                    b.Property<string>("SourceType")
                        .HasColumnType("text");

                    b.Property<string>("ConversationId")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("SourceType", "ConversationId");

                    b.ToTable("bot_conversation_settings", (string)null);
                });

            modelBuilder.Entity("ARCompletions.Domain.BotConversationState", b =>
                {
                    b.Property<string>("SourceType")
                        .HasColumnType("text");

                    b.Property<string>("ConversationId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("HandoffStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("HandoffUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastStaffMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PendingDisambiguationAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PendingDisambiguationIds")
                        .HasColumnType("text");

                    b.Property<string>("PendingDisambiguationRoute")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SourceType", "ConversationId");

                    b.ToTable("bot_conversation_state", (string)null);
                });

            modelBuilder.Entity("ARCompletions.Domain.BotFaqAlias", b =>
                {
                    b.Property<Guid>("AliasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FaqIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Synonyms")
                        .HasColumnType("text");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AliasId");

                    b.ToTable("bot_faq_aliases", (string)null);
                });

            modelBuilder.Entity("ARCompletions.Domain.BotFaqEmbedding", b =>
                {
                    b.Property<Guid>("EmbeddingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<double[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmbeddingProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaqId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RebuiltAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SearchText")
                        .HasColumnType("text");

                    b.Property<int>("VectorDim")
                        .HasColumnType("integer");

                    b.HasKey("EmbeddingId");

                    b.ToTable("bot_faq_embeddings", (string)null);
                });

            modelBuilder.Entity("ARCompletions.Domain.BotFaqItem", b =>
                {
                    b.Property<string>("FaqId")
                        .HasColumnType("text");

                    b.Property<string>("AliasTerms")
                        .HasColumnType("text");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("CategoryKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Keywords")
                        .HasColumnType("text");

                    b.Property<bool>("NeedsHumanHandoff")
                        .HasColumnType("boolean");

                    b.Property<string>("QueryExamples")
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchTextCache")
                        .HasColumnType("text");

                    b.Property<string>("Sources")
                        .HasColumnType("text");

                    b.Property<string>("Subcategory")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("FaqId");

                    b.ToTable("bot_faq_items", (string)null);
                });

            modelBuilder.Entity("ARCompletions.Domain.BotIncomingEvent", b =>
                {
                    b.Property<long>("EventRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EventRowId"));

                    b.Property<string>("ConversationId")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .HasColumnType("text");

                    b.Property<string>("LineGroupId")
                        .HasColumnType("text");

                    b.Property<string>("LineRoomId")
                        .HasColumnType("text");

                    b.Property<string>("LineUserId")
                        .HasColumnType("text");

                    b.Property<string>("MessageType")
                        .HasColumnType("text");

                    b.Property<string>("RawEventJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplyToken")
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .HasColumnType("text");

                    b.HasKey("EventRowId");

                    b.ToTable("bot_incoming_events", (string)null);
                });

            modelBuilder.Entity("ARCompletions.Domain.BotLlmLog", b =>
                {
                    b.Property<long>("LlmLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LlmLogId"));

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<long?>("EventRowId")
                        .HasColumnType("bigint");

                    b.Property<string>("FaqId")
                        .HasColumnType("text");

                    b.Property<string>("LogEvent")
                        .HasColumnType("text");

                    b.Property<string>("MatchedBy")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("ReplyMode")
                        .HasColumnType("text");

                    b.Property<string>("Task")
                        .HasColumnType("text");

                    b.HasKey("LlmLogId");

                    b.ToTable("bot_llm_logs", (string)null);
                });

            modelBuilder.Entity("ARCompletions.Domain.BotMessageRoute", b =>
                {
                    b.Property<long>("RouteRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RouteRowId"));

                    b.Property<string>("AliasTerm")
                        .HasColumnType("text");

                    b.Property<int?>("ContextCountAfter")
                        .HasColumnType("integer");

                    b.Property<int?>("ContextCountBefore")
                        .HasColumnType("integer");

                    b.Property<string>("ConversationId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("EventRowId")
                        .HasColumnType("bigint");

                    b.Property<string>("FaqCategory")
                        .HasColumnType("text");

                    b.Property<bool?>("IsStaffTriggered")
                        .HasColumnType("boolean");

                    b.Property<string>("LineUserId")
                        .HasColumnType("text");

                    b.Property<bool?>("LlmEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LogClass")
                        .HasColumnType("text");

                    b.Property<string>("LogEvent")
                        .HasColumnType("text");

                    b.Property<string>("LogGroup")
                        .HasColumnType("text");

                    b.Property<string>("LogPriority")
                        .HasColumnType("text");

                    b.Property<bool?>("LogUseful")
                        .HasColumnType("boolean");

                    b.Property<string>("MatchedBy")
                        .HasColumnType("text");

                    b.Property<string>("MatchedFaqId")
                        .HasColumnType("text");

                    b.Property<double?>("MatchedScore")
                        .HasColumnType("double precision");

                    b.Property<bool?>("NeedsHumanHandoff")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("ReplyText")
                        .HasColumnType("text");

                    b.Property<string>("Route")
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .HasColumnType("text");

                    b.Property<string>("TopFaqIds")
                        .HasColumnType("text");

                    b.HasKey("RouteRowId");

                    b.ToTable("bot_message_routes", (string)null);
                });

            modelBuilder.Entity("ARCompletions.Domain.BotStaffUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("bot_staff_users", (string)null);
                });

            modelBuilder.Entity("ARCompletions.Domain.BotSystemPrompt", b =>
                {
                    b.Property<string>("PromptKey")
                        .HasColumnType("text");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("PromptKey");

                    b.ToTable("bot_system_prompts", (string)null);
                });

            modelBuilder.Entity("ARCompletions.Domain.PlatformPermission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GroupName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlatformPermissions");
                });

            modelBuilder.Entity("ARCompletions.Domain.PlatformRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlatformRoles");
                });

            modelBuilder.Entity("ARCompletions.Domain.PlatformRolePermission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("PlatformPermissionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformRoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlatformRolePermissions");
                });

            modelBuilder.Entity("ARCompletions.Domain.PlatformUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text");

                    b.Property<long?>("LastLoginAt")
                        .HasColumnType("bigint");

                    b.Property<string>("LastLoginIp")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlatformUsers");
                });

            modelBuilder.Entity("ARCompletions.Domain.PlatformUserRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("PlatformRoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlatformUserRoles");
                });

            modelBuilder.Entity("ARCompletions.Domain.SystemSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
