// <auto-generated />
using System;
using ARCompletions.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ARCompletions.migrations
{
    [DbContext(typeof(ARCompletionsContext))]
    [Migration("20260330140000_AddLineEventLogAndMessageRouteModels")]
    partial class AddLineEventLogAndMessageRouteModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // The full model snapshot is contained in ARCompletionsContextModelSnapshot.
            // This designer intentionally keeps a minimal BuildTargetModel to satisfy EF tooling.
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");
#pragma warning restore 612, 618
        }
    }
}
