// <auto-generated />
using System;
using ARCompletions.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ARCompletions.migrations
{
    [DbContext(typeof(ARCompletionsContext))]
    partial class ARCompletionsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ARCompletions.Data.AnalysisDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CompletionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<double>("Similarity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("AnalysisDetails");
                });

            modelBuilder.Entity("ARCompletions.Data.AnalysisJob", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Params")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<string>("ResultSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("AnalysisJobs");
                });

            modelBuilder.Entity("ARCompletions.Data.AuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ARCompletions.Data.ChatEmbedding", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ChatMessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("EmbeddingJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChatEmbeddings");
                });

            modelBuilder.Entity("ARCompletions.Data.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("ARCompletions.Data.Completion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Complate")
                        .HasColumnType("boolean");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VenuesId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Completions");
                });

            modelBuilder.Entity("ARCompletions.Data.Feedback", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("ARCompletions.Data.LineEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<string>("RawEvent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ReceivedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("LineEvents");
                });

            modelBuilder.Entity("ARCompletions.Data.LineEventLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LineUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageType")
                        .HasColumnType("text");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");
                    b.Property<string>("MessageResultId").HasColumnType("text");
                    b.Property<string>("ProcessingStatus").HasColumnType("text");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LineUserId");

                    b.ToTable("LineEventLogs");
                });

            modelBuilder.Entity("ARCompletions.Data.LineUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<bool>("IsFollowed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LineUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LineUserId")
                        .IsUnique();

                    b.ToTable("LineUsers");
                });

            modelBuilder.Entity("ARCompletions.Data.UnmatchedQuery", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("UnmatchedQueries");
                });

            modelBuilder.Entity("ARCompletions.Domain.MessageResult", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConversationId")
                        .HasColumnType("text");

                    b.Property<string>("MessageId")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("MatchedFaqId")
                        .HasColumnType("text");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("VendorId")
                        .HasColumnType("text");

                    b.Property<string>("Route")
                        .HasColumnType("text");

                    b.Property<string>("MessageRouteId")
                        .HasColumnType("text");

                    b.Property<string>("MatchedBy")
                        .HasColumnType("text");

                    b.Property<double?>("MatchedScore")
                        .HasColumnType("double precision");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("MessageResults");
                });

            modelBuilder.Entity("ARCompletions.Domain.FaqQueryLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("MessageResultId")
                        .HasColumnType("text");

                    b.Property<string>("QueryText")
                        .HasColumnType("text");

                    b.Property<string>("MatchedFaqId")
                        .HasColumnType("text");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("FaqQueryLogs");
                });

            modelBuilder.Entity("ARCompletions.Domain.ConversationState", b =>
                {
                    b.Property<string>("Id").HasColumnType("text");

                    b.Property<string>("VendorId").IsRequired().HasColumnType("text");
                    b.Property<string>("SourceType").IsRequired().HasColumnType("text");
                    b.Property<string>("ConversationId").IsRequired().HasColumnType("text");
                    b.Property<bool>("BotEnabled").HasColumnType("boolean");
                    b.Property<long?>("HandoffUntil").HasColumnType("bigint");
                    b.Property<string>("PendingDisambiguationIds").HasColumnType("text");
                    b.Property<long?>("PendingDisambiguationAt").HasColumnType("bigint");
                    b.Property<long?>("LastStaffMessageAt").HasColumnType("bigint");
                    b.Property<long>("UpdatedAt").HasColumnType("bigint");
                    b.Property<string>("UpdatedBy").HasColumnType("text");

                    b.HasKey("Id");
                    b.HasIndex("VendorId", "SourceType", "ConversationId").IsUnique();
                    b.ToTable("ConversationStates");
                });

            modelBuilder.Entity("ARCompletions.Domain.FaqAlias", b =>
                {
                    b.Property<string>("Id").HasColumnType("text");
                    b.Property<string>("VendorId").IsRequired().HasColumnType("text");
                    b.Property<string>("Term").IsRequired().HasColumnType("text");
                    b.Property<string>("Synonyms").HasColumnType("text");
                    b.Property<string>("Mode").IsRequired().HasColumnType("text");
                    b.Property<string>("FaqIds").IsRequired().HasColumnType("text");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<long>("CreatedAt").HasColumnType("bigint");
                    b.Property<string>("CreatedBy").HasColumnType("text");
                    b.Property<long?>("UpdatedAt").HasColumnType("bigint");
                    b.Property<string>("UpdatedBy").HasColumnType("text");

                    b.HasKey("Id");
                    b.ToTable("FaqAliases");
                });

            modelBuilder.Entity("ARCompletions.Domain.MessageRoute", b =>
                {
                    b.Property<string>("Id").HasColumnType("text");
                    b.Property<string>("VendorId").IsRequired().HasColumnType("text");
                    b.Property<string>("InputLogId").HasColumnType("text");
                    b.Property<string>("ConversationId").HasColumnType("text");
                    b.Property<string>("Route").IsRequired().HasColumnType("text");
                    b.Property<string>("Reason").HasColumnType("text");
                    b.Property<string>("MatchedFaqId").HasColumnType("text");
                    b.Property<double?>("MatchedScore").HasColumnType("double precision");
                    b.Property<string>("MatchedBy").HasColumnType("text");
                    b.Property<string>("FaqCategory").HasColumnType("text");
                    b.Property<bool>("LlmEnabled").HasColumnType("boolean");
                    b.Property<string>("LlmModel").HasColumnType("text");
                    b.Property<string>("EmbeddingModel").HasColumnType("text");
                    b.Property<bool>("NeedsHandoff").HasColumnType("boolean");
                    b.Property<string>("ReplyText").HasColumnType("text");
                    b.Property<long>("CreatedAt").HasColumnType("bigint");

                    b.HasKey("Id");
                    b.HasIndex("VendorId");
                    b.HasIndex("InputLogId");
                    b.HasIndex("Route");
                    b.HasIndex("CreatedAt");
                    b.ToTable("MessageRoutes");
                });

            modelBuilder.Entity("ARCompletions.Domain.VendorStaffUser", b =>
                {
                    b.Property<string>("Id").HasColumnType("text");
                    b.Property<string>("VendorId").IsRequired().HasColumnType("text");
                    b.Property<string>("LineUserId").IsRequired().HasColumnType("text");
                    b.Property<string>("Name").HasColumnType("text");
                    b.Property<string>("Role").HasColumnType("text");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<long>("CreatedAt").HasColumnType("bigint");
                    b.Property<string>("CreatedBy").HasColumnType("text");
                    b.Property<long?>("UpdatedAt").HasColumnType("bigint");
                    b.Property<string>("UpdatedBy").HasColumnType("text");

                    b.HasKey("Id");
                    b.HasIndex("VendorId", "LineUserId").IsUnique();
                    b.ToTable("VendorStaffUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
